default:
  image: node:22.1.0-alpine
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install --progress=false
    - npm test

pages:
 stage: deploy
 script:
  - npm install --progress=false
  - npm run build
  - rm -rf public
  - mkdir public
  - cp -r dist/* public
 artifacts:
  paths:
  - public
 only:
  - main